# Generated by Django 5.1.4 on 2024-12-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='start_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='start_price'),
        ),
    ]
